[package]
name = "rust-todo-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
dotenvy = "0.15.7"
openssl = "0.10.73"
postgres = "0.19.10"
postgres-openssl = "0.5.1"